// Targeted by JavaCPP version 1.5.10: DO NOT EDIT THIS FILE

package us.ihmc.remotecaptury;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import static us.ihmc.remotecaptury.global.remotecaptury.*;


@Properties(inherit = us.ihmc.remotecaptury.RemoteCapturyConfig.class)
public class CapturyPoseCont extends Pointer {
    static { Loader.load(); }
    /** Default native constructor. */
    public CapturyPoseCont() { super((Pointer)null); allocate(); }
    /** Native array allocator. Access with {@link Pointer#position(long)}. */
    public CapturyPoseCont(long size) { super((Pointer)null); allocateArray(size); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public CapturyPoseCont(Pointer p) { super(p); }
    private native void allocate();
    private native void allocateArray(long size);
    @Override public CapturyPoseCont position(long position) {
        return (CapturyPoseCont)super.position(position);
    }
    @Override public CapturyPoseCont getPointer(long i) {
        return new CapturyPoseCont((Pointer)this).offsetAddress(i);
    }

	public native int type(); public native CapturyPoseCont type(int setter);	// capturyPoseCont
	public native int size(); public native CapturyPoseCont size(int setter);	// size of full message including type and size

	public native int actor(); public native CapturyPoseCont actor(int setter);
	public native @Cast("uint64_t") long timestamp(); public native CapturyPoseCont timestamp(long setter);
	public native float values(int i); public native CapturyPoseCont values(int i, float setter);
	@MemberGetter public native FloatPointer values();
}
