// Targeted by JavaCPP version 1.5.10: DO NOT EDIT THIS FILE

package us.ihmc.remotecaptury;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import static us.ihmc.remotecaptury.global.remotecaptury.*;

@Properties(inherit = us.ihmc.remotecaptury.RemoteCapturyConfig.class)
public class CapturyAngleData extends Pointer {
    static { Loader.load(); }
    /** Default native constructor. */
    public CapturyAngleData() { super((Pointer)null); allocate(); }
    /** Native array allocator. Access with {@link Pointer#position(long)}. */
    public CapturyAngleData(long size) { super((Pointer)null); allocateArray(size); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public CapturyAngleData(Pointer p) { super(p); }
    private native void allocate();
    private native void allocateArray(long size);
    @Override public CapturyAngleData position(long position) {
        return (CapturyAngleData)super.position(position);
    }
    @Override public CapturyAngleData getPointer(long i) {
        return new CapturyAngleData((Pointer)this).offsetAddress(i);
    }

	public native @Cast("uint16_t") short type(); public native CapturyAngleData type(short setter);
	public native float value(); public native CapturyAngleData value(float setter);
}
