// Targeted by JavaCPP version 1.5.10: DO NOT EDIT THIS FILE

package us.ihmc.remotecaptury;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import static us.ihmc.remotecaptury.global.remotecaptury.*;


// sent to server
@Properties(inherit = us.ihmc.remotecaptury.RemoteCapturyConfig.class)
public class CapturyConstraintPacket extends Pointer {
    static { Loader.load(); }
    /** Default native constructor. */
    public CapturyConstraintPacket() { super((Pointer)null); allocate(); }
    /** Native array allocator. Access with {@link Pointer#position(long)}. */
    public CapturyConstraintPacket(long size) { super((Pointer)null); allocateArray(size); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public CapturyConstraintPacket(Pointer p) { super(p); }
    private native void allocate();
    private native void allocateArray(long size);
    @Override public CapturyConstraintPacket position(long position) {
        return (CapturyConstraintPacket)super.position(position);
    }
    @Override public CapturyConstraintPacket getPointer(long i) {
        return new CapturyConstraintPacket((Pointer)this).offsetAddress(i);
    }

	public native int type(); public native CapturyConstraintPacket type(int setter);	// capturyConstraint
	public native int size(); public native CapturyConstraintPacket size(int setter);

	public native int constrType(); public native CapturyConstraintPacket constrType(int setter);

	public native int originActor(); public native CapturyConstraintPacket originActor(int setter);
	public native int originJoint(); public native CapturyConstraintPacket originJoint(int setter);
	public native float originOffset(int i); public native CapturyConstraintPacket originOffset(int i, float setter);
	@MemberGetter public native FloatPointer originOffset();

	public native int targetActor(); public native CapturyConstraintPacket targetActor(int setter);
	public native int targetJoint(); public native CapturyConstraintPacket targetJoint(int setter);
	public native float targetOffset(int i); public native CapturyConstraintPacket targetOffset(int i, float setter);
	@MemberGetter public native FloatPointer targetOffset();

	public native float targetVector(int i); public native CapturyConstraintPacket targetVector(int i, float setter);
	@MemberGetter public native FloatPointer targetVector();
	public native float targetValue(); public native CapturyConstraintPacket targetValue(float setter);
	public native float targetRotation(int i); public native CapturyConstraintPacket targetRotation(int i, float setter);
	@MemberGetter public native FloatPointer targetRotation();

	public native float weight(); public native CapturyConstraintPacket weight(float setter);
}
