// Targeted by JavaCPP version 1.5.10: DO NOT EDIT THIS FILE

package us.ihmc.remotecaptury;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import static us.ihmc.remotecaptury.global.remotecaptury.*;


// sent to server
@Properties(inherit = us.ihmc.remotecaptury.RemoteCapturyConfig.class)
public class CapturySetShotPacket extends Pointer {
    static { Loader.load(); }
    /** Default native constructor. */
    public CapturySetShotPacket() { super((Pointer)null); allocate(); }
    /** Native array allocator. Access with {@link Pointer#position(long)}. */
    public CapturySetShotPacket(long size) { super((Pointer)null); allocateArray(size); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public CapturySetShotPacket(Pointer p) { super(p); }
    private native void allocate();
    private native void allocateArray(long size);
    @Override public CapturySetShotPacket position(long position) {
        return (CapturySetShotPacket)super.position(position);
    }
    @Override public CapturySetShotPacket getPointer(long i) {
        return new CapturySetShotPacket((Pointer)this).offsetAddress(i);
    }

	public native int type(); public native CapturySetShotPacket type(int setter);	// capturySetShot
	public native int size(); public native CapturySetShotPacket size(int setter);	// size of full message including type and size

	public native @Cast("char") byte shot(int i); public native CapturySetShotPacket shot(int i, byte setter);
	@MemberGetter public native @Cast("char*") BytePointer shot();
}
