// Targeted by JavaCPP version 1.5.10: DO NOT EDIT THIS FILE

package us.ihmc.remotecaptury;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import static us.ihmc.remotecaptury.global.remotecaptury.*;


// sent to server
@Properties(inherit = us.ihmc.remotecaptury.RemoteCapturyConfig.class)
public class CapturyStreamPacketTcp extends Pointer {
    static { Loader.load(); }
    /** Default native constructor. */
    public CapturyStreamPacketTcp() { super((Pointer)null); allocate(); }
    /** Native array allocator. Access with {@link Pointer#position(long)}. */
    public CapturyStreamPacketTcp(long size) { super((Pointer)null); allocateArray(size); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public CapturyStreamPacketTcp(Pointer p) { super(p); }
    private native void allocate();
    private native void allocateArray(long size);
    @Override public CapturyStreamPacketTcp position(long position) {
        return (CapturyStreamPacketTcp)super.position(position);
    }
    @Override public CapturyStreamPacketTcp getPointer(long i) {
        return new CapturyStreamPacketTcp((Pointer)this).offsetAddress(i);
    }

	public native int type(); public native CapturyStreamPacketTcp type(int setter);		// capturyStream
	public native int size(); public native CapturyStreamPacketTcp size(int setter);		// size of full message including type and size

	public native int what(); public native CapturyStreamPacketTcp what(int setter);		// CAPTURY_STREAM_POSES or CAPTURY_STREAM_NOTHING
	public native int cameraId(); public native CapturyStreamPacketTcp cameraId(int setter);	// valid if what & CAPTURY_STREAM_IMAGES

	public native @Cast("uint32_t") int ip(); public native CapturyStreamPacketTcp ip(int setter);		// where to stream to
	public native @Cast("uint16_t") short port(); public native CapturyStreamPacketTcp port(short setter);
}
