// Targeted by JavaCPP version 1.5.10: DO NOT EDIT THIS FILE

package us.ihmc.remotecaptury;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import static us.ihmc.remotecaptury.global.remotecaptury.*;


@Properties(inherit = us.ihmc.remotecaptury.RemoteCapturyConfig.class)
public class CapturyStartTrackingPacket extends Pointer {
    static { Loader.load(); }
    /** Default native constructor. */
    public CapturyStartTrackingPacket() { super((Pointer)null); allocate(); }
    /** Native array allocator. Access with {@link Pointer#position(long)}. */
    public CapturyStartTrackingPacket(long size) { super((Pointer)null); allocateArray(size); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public CapturyStartTrackingPacket(Pointer p) { super(p); }
    private native void allocate();
    private native void allocateArray(long size);
    @Override public CapturyStartTrackingPacket position(long position) {
        return (CapturyStartTrackingPacket)super.position(position);
    }
    @Override public CapturyStartTrackingPacket getPointer(long i) {
        return new CapturyStartTrackingPacket((Pointer)this).offsetAddress(i);
    }

	public native int type(); public native CapturyStartTrackingPacket type(int setter); // capturyStartTracking
	public native int size(); public native CapturyStartTrackingPacket size(int setter);

	public native int actor(); public native CapturyStartTrackingPacket actor(int setter);
	public native float x(); public native CapturyStartTrackingPacket x(float setter);
	public native float z(); public native CapturyStartTrackingPacket z(float setter);
	public native float heading(); public native CapturyStartTrackingPacket heading(float setter);
}
