// Targeted by JavaCPP version 1.5.10: DO NOT EDIT THIS FILE

package us.ihmc.remotecaptury;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import static us.ihmc.remotecaptury.global.remotecaptury.*;


// sent to client
// as a reply to capturyGetTime2
@Properties(inherit = us.ihmc.remotecaptury.RemoteCapturyConfig.class)
public class CapturyTimePacket2 extends Pointer {
    static { Loader.load(); }
    /** Default native constructor. */
    public CapturyTimePacket2() { super((Pointer)null); allocate(); }
    /** Native array allocator. Access with {@link Pointer#position(long)}. */
    public CapturyTimePacket2(long size) { super((Pointer)null); allocateArray(size); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public CapturyTimePacket2(Pointer p) { super(p); }
    private native void allocate();
    private native void allocateArray(long size);
    @Override public CapturyTimePacket2 position(long position) {
        return (CapturyTimePacket2)super.position(position);
    }
    @Override public CapturyTimePacket2 getPointer(long i) {
        return new CapturyTimePacket2((Pointer)this).offsetAddress(i);
    }

	public native int type(); public native CapturyTimePacket2 type(int setter);	// capturyGetTime2, capturyTime2
	public native int size(); public native CapturyTimePacket2 size(int setter);

	public native @Cast("uint64_t") long timestamp(); public native CapturyTimePacket2 timestamp(long setter);

	public native int timeId(); public native CapturyTimePacket2 timeId(int setter); // set by remote client and repeated by server
}
