// Targeted by JavaCPP version 1.5.10: DO NOT EDIT THIS FILE

package us.ihmc.remotecaptury;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import static us.ihmc.remotecaptury.global.remotecaptury.*;


@Properties(inherit = us.ihmc.remotecaptury.RemoteCapturyConfig.class)
public class CapturyStatusPacket extends Pointer {
    static { Loader.load(); }
    /** Default native constructor. */
    public CapturyStatusPacket() { super((Pointer)null); allocate(); }
    /** Native array allocator. Access with {@link Pointer#position(long)}. */
    public CapturyStatusPacket(long size) { super((Pointer)null); allocateArray(size); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public CapturyStatusPacket(Pointer p) { super(p); }
    private native void allocate();
    private native void allocateArray(long size);
    @Override public CapturyStatusPacket position(long position) {
        return (CapturyStatusPacket)super.position(position);
    }
    @Override public CapturyStatusPacket getPointer(long i) {
        return new CapturyStatusPacket((Pointer)this).offsetAddress(i);
    }

	public native int type(); public native CapturyStatusPacket type(int setter); // capturyStatus
	public native int size(); public native CapturyStatusPacket size(int setter);
	public native @Cast("char") byte message(int i); public native CapturyStatusPacket message(int i, byte setter);
	@MemberGetter public native @Cast("char*") BytePointer message(); // 0-terminated
}
