// Targeted by JavaCPP version 1.5.10: DO NOT EDIT THIS FILE

package us.ihmc.remotecaptury;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import static us.ihmc.remotecaptury.global.remotecaptury.*;


@Properties(inherit = us.ihmc.remotecaptury.RemoteCapturyConfig.class)
public class CapturyGetImageDataPacket extends Pointer {
    static { Loader.load(); }
    /** Default native constructor. */
    public CapturyGetImageDataPacket() { super((Pointer)null); allocate(); }
    /** Native array allocator. Access with {@link Pointer#position(long)}. */
    public CapturyGetImageDataPacket(long size) { super((Pointer)null); allocateArray(size); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public CapturyGetImageDataPacket(Pointer p) { super(p); }
    private native void allocate();
    private native void allocateArray(long size);
    @Override public CapturyGetImageDataPacket position(long position) {
        return (CapturyGetImageDataPacket)super.position(position);
    }
    @Override public CapturyGetImageDataPacket getPointer(long i) {
        return new CapturyGetImageDataPacket((Pointer)this).offsetAddress(i);
    }

	public native int type(); public native CapturyGetImageDataPacket type(int setter);	// capturyGetImageData
	public native int size(); public native CapturyGetImageDataPacket size(int setter);

	public native @Cast("uint16_t") short port(); public native CapturyGetImageDataPacket port(short setter);
	public native int actor(); public native CapturyGetImageDataPacket actor(int setter);
}
