// Targeted by JavaCPP version 1.5.10: DO NOT EDIT THIS FILE

package us.ihmc.remotecaptury;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import static us.ihmc.remotecaptury.global.remotecaptury.*;


// sent to client
// as a reply to CapturyRequestPacket = capturyActors
@Properties(inherit = us.ihmc.remotecaptury.RemoteCapturyConfig.class)
public class CapturyActorsPacket extends Pointer {
    static { Loader.load(); }
    /** Default native constructor. */
    public CapturyActorsPacket() { super((Pointer)null); allocate(); }
    /** Native array allocator. Access with {@link Pointer#position(long)}. */
    public CapturyActorsPacket(long size) { super((Pointer)null); allocateArray(size); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public CapturyActorsPacket(Pointer p) { super(p); }
    private native void allocate();
    private native void allocateArray(long size);
    @Override public CapturyActorsPacket position(long position) {
        return (CapturyActorsPacket)super.position(position);
    }
    @Override public CapturyActorsPacket getPointer(long i) {
        return new CapturyActorsPacket((Pointer)this).offsetAddress(i);
    }

	public native int type(); public native CapturyActorsPacket type(int setter);	// capturyActors
	public native int size(); public native CapturyActorsPacket size(int setter);	// size of full message including type and size

	public native int numActors(); public native CapturyActorsPacket numActors(int setter);
}
