// Targeted by JavaCPP version 1.5.10: DO NOT EDIT THIS FILE

package us.ihmc.remotecaptury;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import static us.ihmc.remotecaptury.global.remotecaptury.*;


// sent to server
@Properties(inherit = us.ihmc.remotecaptury.RemoteCapturyConfig.class)
public class CapturyStreamPacket1Tcp extends Pointer {
    static { Loader.load(); }
    /** Default native constructor. */
    public CapturyStreamPacket1Tcp() { super((Pointer)null); allocate(); }
    /** Native array allocator. Access with {@link Pointer#position(long)}. */
    public CapturyStreamPacket1Tcp(long size) { super((Pointer)null); allocateArray(size); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public CapturyStreamPacket1Tcp(Pointer p) { super(p); }
    private native void allocate();
    private native void allocateArray(long size);
    @Override public CapturyStreamPacket1Tcp position(long position) {
        return (CapturyStreamPacket1Tcp)super.position(position);
    }
    @Override public CapturyStreamPacket1Tcp getPointer(long i) {
        return new CapturyStreamPacket1Tcp((Pointer)this).offsetAddress(i);
    }

	public native int type(); public native CapturyStreamPacket1Tcp type(int setter);		// capturyStream
	public native int size(); public native CapturyStreamPacket1Tcp size(int setter);		// size of full message including type and size

	public native int what(); public native CapturyStreamPacket1Tcp what(int setter);		// CAPTURY_STREAM_POSES or CAPTURY_STREAM_NOTHING
	public native int cameraId(); public native CapturyStreamPacket1Tcp cameraId(int setter);	// valid if what & CAPTURY_STREAM_IMAGES

	public native @Cast("uint32_t") int ip(); public native CapturyStreamPacket1Tcp ip(int setter);		// where to stream to
	public native @Cast("uint16_t") short port(); public native CapturyStreamPacket1Tcp port(short setter);

	public native @Cast("uint16_t") short numAngles(); public native CapturyStreamPacket1Tcp numAngles(short setter);
	public native @Cast("uint16_t") short angles(int i); public native CapturyStreamPacket1Tcp angles(int i, short setter);
	@MemberGetter public native @Cast("uint16_t*") ShortPointer angles();
}
