// Targeted by JavaCPP version 1.5.10: DO NOT EDIT THIS FILE

package us.ihmc.remotecaptury;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import static us.ihmc.remotecaptury.global.remotecaptury.*;


@Properties(inherit = us.ihmc.remotecaptury.RemoteCapturyConfig.class)
public class CapturyBlob extends Pointer {
    static { Loader.load(); }
    /** Default native constructor. */
    public CapturyBlob() { super((Pointer)null); allocate(); }
    /** Native array allocator. Access with {@link Pointer#position(long)}. */
    public CapturyBlob(long size) { super((Pointer)null); allocateArray(size); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public CapturyBlob(Pointer p) { super(p); }
    private native void allocate();
    private native void allocateArray(long size);
    @Override public CapturyBlob position(long position) {
        return (CapturyBlob)super.position(position);
    }
    @Override public CapturyBlob getPointer(long i) {
        return new CapturyBlob((Pointer)this).offsetAddress(i);
    }

	public native int parent(); public native CapturyBlob parent(int setter);		// index of parent joint or -1 for root node
	public native float offset(int i); public native CapturyBlob offset(int i, float setter);
	@MemberGetter public native FloatPointer offset();	// offset to parent joint
	public native float size(); public native CapturyBlob size(float setter);		// radius
	public native float color(int i); public native CapturyBlob color(int i, float setter);
	@MemberGetter public native FloatPointer color();	// RGB color [0..1]
}
