// Targeted by JavaCPP version 1.5.10: DO NOT EDIT THIS FILE

package us.ihmc.remotecaptury;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import static us.ihmc.remotecaptury.global.remotecaptury.*;


// sent to server
@Properties(inherit = us.ihmc.remotecaptury.RemoteCapturyConfig.class)
public class CapturyGetScalingProgressPacket extends Pointer {
    static { Loader.load(); }
    /** Default native constructor. */
    public CapturyGetScalingProgressPacket() { super((Pointer)null); allocate(); }
    /** Native array allocator. Access with {@link Pointer#position(long)}. */
    public CapturyGetScalingProgressPacket(long size) { super((Pointer)null); allocateArray(size); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public CapturyGetScalingProgressPacket(Pointer p) { super(p); }
    private native void allocate();
    private native void allocateArray(long size);
    @Override public CapturyGetScalingProgressPacket position(long position) {
        return (CapturyGetScalingProgressPacket)super.position(position);
    }
    @Override public CapturyGetScalingProgressPacket getPointer(long i) {
        return new CapturyGetScalingProgressPacket((Pointer)this).offsetAddress(i);
    }

	public native int type(); public native CapturyGetScalingProgressPacket type(int setter);	// capturyGetScalingProgress
	public native int size(); public native CapturyGetScalingProgressPacket size(int setter);

	public native int actor(); public native CapturyGetScalingProgressPacket actor(int setter);
}
