// Targeted by JavaCPP version 1.5.10: DO NOT EDIT THIS FILE

package us.ihmc.remotecaptury;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import static us.ihmc.remotecaptury.global.remotecaptury.*;


// sent to client
// part of CapturyActorPacket
@Properties(inherit = us.ihmc.remotecaptury.RemoteCapturyConfig.class)
public class CapturyJointPacket extends Pointer {
    static { Loader.load(); }
    /** Default native constructor. */
    public CapturyJointPacket() { super((Pointer)null); allocate(); }
    /** Native array allocator. Access with {@link Pointer#position(long)}. */
    public CapturyJointPacket(long size) { super((Pointer)null); allocateArray(size); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public CapturyJointPacket(Pointer p) { super(p); }
    private native void allocate();
    private native void allocateArray(long size);
    @Override public CapturyJointPacket position(long position) {
        return (CapturyJointPacket)super.position(position);
    }
    @Override public CapturyJointPacket getPointer(long i) {
        return new CapturyJointPacket((Pointer)this).offsetAddress(i);
    }

	public native @Cast("char") byte name(int i); public native CapturyJointPacket name(int i, byte setter);
	@MemberGetter public native @Cast("char*") BytePointer name();
	public native int parent(); public native CapturyJointPacket parent(int setter);
	public native float offset(int i); public native CapturyJointPacket offset(int i, float setter);
	@MemberGetter public native FloatPointer offset();
	public native float orientation(int i); public native CapturyJointPacket orientation(int i, float setter);
	@MemberGetter public native FloatPointer orientation();
}
