// Targeted by JavaCPP version 1.5.10: DO NOT EDIT THIS FILE

package us.ihmc.remotecaptury;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import static us.ihmc.remotecaptury.global.remotecaptury.*;


// sent to client
// as a reply to CapturyStreamPacket
@Properties(inherit = us.ihmc.remotecaptury.RemoteCapturyConfig.class)
public class CapturyPosePacket extends Pointer {
    static { Loader.load(); }
    /** Default native constructor. */
    public CapturyPosePacket() { super((Pointer)null); allocate(); }
    /** Native array allocator. Access with {@link Pointer#position(long)}. */
    public CapturyPosePacket(long size) { super((Pointer)null); allocateArray(size); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public CapturyPosePacket(Pointer p) { super(p); }
    private native void allocate();
    private native void allocateArray(long size);
    @Override public CapturyPosePacket position(long position) {
        return (CapturyPosePacket)super.position(position);
    }
    @Override public CapturyPosePacket getPointer(long i) {
        return new CapturyPosePacket((Pointer)this).offsetAddress(i);
    }

	public native int type(); public native CapturyPosePacket type(int setter);	// capturyPose
	public native int size(); public native CapturyPosePacket size(int setter);	// size of full message including type and size

	public native int actor(); public native CapturyPosePacket actor(int setter);
	public native @Cast("uint64_t") long timestamp(); public native CapturyPosePacket timestamp(long setter);
	public native int numValues(); public native CapturyPosePacket numValues(int setter); // 6 * numJoints + numBlendShapes + (numJoints if scale is enabled)
	public native float values(int i); public native CapturyPosePacket values(int i, float setter);
	@MemberGetter public native FloatPointer values();
}
