// Targeted by JavaCPP version 1.5.10: DO NOT EDIT THIS FILE

package us.ihmc.remotecaptury;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import static us.ihmc.remotecaptury.global.remotecaptury.*;


@Properties(inherit = us.ihmc.remotecaptury.RemoteCapturyConfig.class)
public class CapturyJoint extends Pointer {
    static { Loader.load(); }
    /** Default native constructor. */
    public CapturyJoint() { super((Pointer)null); allocate(); }
    /** Native array allocator. Access with {@link Pointer#position(long)}. */
    public CapturyJoint(long size) { super((Pointer)null); allocateArray(size); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public CapturyJoint(Pointer p) { super(p); }
    private native void allocate();
    private native void allocateArray(long size);
    @Override public CapturyJoint position(long position) {
        return (CapturyJoint)super.position(position);
    }
    @Override public CapturyJoint getPointer(long i) {
        return new CapturyJoint((Pointer)this).offsetAddress(i);
    }

	public native @Cast("char") byte name(int i); public native CapturyJoint name(int i, byte setter);
	@MemberGetter public native @Cast("char*") BytePointer name();
	public native int parent(); public native CapturyJoint parent(int setter);		// index of parent joint or -1 for root node
	public native float offset(int i); public native CapturyJoint offset(int i, float setter);
	@MemberGetter public native FloatPointer offset();	// offset to parent joint
	public native float orientation(int i); public native CapturyJoint orientation(int i, float setter);
	@MemberGetter public native FloatPointer orientation();	// XYZ quaternion - w needs to be reconstructed (w >= 0)
	public native float scale(int i); public native CapturyJoint scale(int i, float setter);
	@MemberGetter public native FloatPointer scale();	// local scale
}
