// Targeted by JavaCPP version 1.5.10: DO NOT EDIT THIS FILE

package us.ihmc.remotecaptury;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import static us.ihmc.remotecaptury.global.remotecaptury.*;


// sent to client
// as a reply to CapturyRequestPacket = capturyCamera
@Properties(inherit = us.ihmc.remotecaptury.RemoteCapturyConfig.class)
public class CapturyCameraPacket extends Pointer {
    static { Loader.load(); }
    /** Default native constructor. */
    public CapturyCameraPacket() { super((Pointer)null); allocate(); }
    /** Native array allocator. Access with {@link Pointer#position(long)}. */
    public CapturyCameraPacket(long size) { super((Pointer)null); allocateArray(size); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public CapturyCameraPacket(Pointer p) { super(p); }
    private native void allocate();
    private native void allocateArray(long size);
    @Override public CapturyCameraPacket position(long position) {
        return (CapturyCameraPacket)super.position(position);
    }
    @Override public CapturyCameraPacket getPointer(long i) {
        return new CapturyCameraPacket((Pointer)this).offsetAddress(i);
    }

	public native int type(); public native CapturyCameraPacket type(int setter);	// capturyCamera
	public native int size(); public native CapturyCameraPacket size(int setter);	// size of full message including type and size

	public native @Cast("char") byte name(int i); public native CapturyCameraPacket name(int i, byte setter);
	@MemberGetter public native @Cast("char*") BytePointer name();
	public native int id(); public native CapturyCameraPacket id(int setter);
	public native @Name("position") float _position(int i); public native CapturyCameraPacket _position(int i, float setter);
	@MemberGetter public native @Name("position") FloatPointer _position();
	public native float orientation(int i); public native CapturyCameraPacket orientation(int i, float setter);
	@MemberGetter public native FloatPointer orientation();
	public native float sensorSize(int i); public native CapturyCameraPacket sensorSize(int i, float setter);
	@MemberGetter public native FloatPointer sensorSize();	// in mm
	public native float focalLength(); public native CapturyCameraPacket focalLength(float setter);	// in mm
	public native float lensCenter(int i); public native CapturyCameraPacket lensCenter(int i, float setter);
	@MemberGetter public native FloatPointer lensCenter();	// in mm
}
