// Targeted by JavaCPP version 1.5.10: DO NOT EDIT THIS FILE

package us.ihmc.remotecaptury;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import static us.ihmc.remotecaptury.global.remotecaptury.*;


@Properties(inherit = us.ihmc.remotecaptury.RemoteCapturyConfig.class)
public class CapturyARTagPacket extends Pointer {
    static { Loader.load(); }
    /** Default native constructor. */
    public CapturyARTagPacket() { super((Pointer)null); allocate(); }
    /** Native array allocator. Access with {@link Pointer#position(long)}. */
    public CapturyARTagPacket(long size) { super((Pointer)null); allocateArray(size); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public CapturyARTagPacket(Pointer p) { super(p); }
    private native void allocate();
    private native void allocateArray(long size);
    @Override public CapturyARTagPacket position(long position) {
        return (CapturyARTagPacket)super.position(position);
    }
    @Override public CapturyARTagPacket getPointer(long i) {
        return new CapturyARTagPacket((Pointer)this).offsetAddress(i);
    }

	public native int type(); public native CapturyARTagPacket type(int setter); // capturyARTag
	public native int size(); public native CapturyARTagPacket size(int setter);
	public native int numTags(); public native CapturyARTagPacket numTags(int setter);

	public native @ByRef CapturyARTag tags(int i); public native CapturyARTagPacket tags(int i, CapturyARTag setter);
	@MemberGetter public native CapturyARTag tags();
}
