// Targeted by JavaCPP version 1.5.10: DO NOT EDIT THIS FILE

package us.ihmc.remotecaptury;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import static us.ihmc.remotecaptury.global.remotecaptury.*;


// sent to server
@Properties(inherit = us.ihmc.remotecaptury.RemoteCapturyConfig.class)
public class CapturyStreamPacket1 extends Pointer {
    static { Loader.load(); }
    /** Default native constructor. */
    public CapturyStreamPacket1() { super((Pointer)null); allocate(); }
    /** Native array allocator. Access with {@link Pointer#position(long)}. */
    public CapturyStreamPacket1(long size) { super((Pointer)null); allocateArray(size); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public CapturyStreamPacket1(Pointer p) { super(p); }
    private native void allocate();
    private native void allocateArray(long size);
    @Override public CapturyStreamPacket1 position(long position) {
        return (CapturyStreamPacket1)super.position(position);
    }
    @Override public CapturyStreamPacket1 getPointer(long i) {
        return new CapturyStreamPacket1((Pointer)this).offsetAddress(i);
    }

	public native int type(); public native CapturyStreamPacket1 type(int setter);		// capturyStream
	public native int size(); public native CapturyStreamPacket1 size(int setter);		// size of full message including type and size

	public native int what(); public native CapturyStreamPacket1 what(int setter);		// CAPTURY_STREAM_POSES or CAPTURY_STREAM_NOTHING
	public native int cameraId(); public native CapturyStreamPacket1 cameraId(int setter);	// valid if what & CAPTURY_STREAM_IMAGES
	public native @Cast("uint16_t") short numAngles(); public native CapturyStreamPacket1 numAngles(short setter);
	public native @Cast("uint16_t") short angles(int i); public native CapturyStreamPacket1 angles(int i, short setter);
	@MemberGetter public native @Cast("uint16_t*") ShortPointer angles();
}
