// Targeted by JavaCPP version 1.5.10: DO NOT EDIT THIS FILE

package us.ihmc.remotecaptury;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import static us.ihmc.remotecaptury.global.remotecaptury.*;


@Properties(inherit = us.ihmc.remotecaptury.RemoteCapturyConfig.class)
public class CapturyImageDataPacket extends Pointer {
    static { Loader.load(); }
    /** Default native constructor. */
    public CapturyImageDataPacket() { super((Pointer)null); allocate(); }
    /** Native array allocator. Access with {@link Pointer#position(long)}. */
    public CapturyImageDataPacket(long size) { super((Pointer)null); allocateArray(size); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public CapturyImageDataPacket(Pointer p) { super(p); }
    private native void allocate();
    private native void allocateArray(long size);
    @Override public CapturyImageDataPacket position(long position) {
        return (CapturyImageDataPacket)super.position(position);
    }
    @Override public CapturyImageDataPacket getPointer(long i) {
        return new CapturyImageDataPacket((Pointer)this).offsetAddress(i);
    }

	public native int type(); public native CapturyImageDataPacket type(int setter);	// capturyImageData, capturyStreamedImageData
	public native int size(); public native CapturyImageDataPacket size(int setter);

	public native int actor(); public native CapturyImageDataPacket actor(int setter);	// for capturyStreamedImageData this is the camera id
	public native int offset(); public native CapturyImageDataPacket offset(int setter);	// offset in bytes into the following data (0 for first packet)
	public native @Cast("unsigned char") byte data(int i); public native CapturyImageDataPacket data(int i, byte setter);
	@MemberGetter public native @Cast("unsigned char*") BytePointer data();	// width*height*3 bytes
}
