// Targeted by JavaCPP version 1.5.10: DO NOT EDIT THIS FILE

package us.ihmc.remotecaptury;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import static us.ihmc.remotecaptury.global.remotecaptury.*;


// sent to client
// as a reply to capturyGetTime
@Properties(inherit = us.ihmc.remotecaptury.RemoteCapturyConfig.class)
public class CapturyTimePacket extends Pointer {
    static { Loader.load(); }
    /** Default native constructor. */
    public CapturyTimePacket() { super((Pointer)null); allocate(); }
    /** Native array allocator. Access with {@link Pointer#position(long)}. */
    public CapturyTimePacket(long size) { super((Pointer)null); allocateArray(size); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public CapturyTimePacket(Pointer p) { super(p); }
    private native void allocate();
    private native void allocateArray(long size);
    @Override public CapturyTimePacket position(long position) {
        return (CapturyTimePacket)super.position(position);
    }
    @Override public CapturyTimePacket getPointer(long i) {
        return new CapturyTimePacket((Pointer)this).offsetAddress(i);
    }

	public native int type(); public native CapturyTimePacket type(int setter);	// capturyTime, capturyStartRecordingAck2
	public native int size(); public native CapturyTimePacket size(int setter);

	public native @Cast("uint64_t") long timestamp(); public native CapturyTimePacket timestamp(long setter);
}
