// Targeted by JavaCPP version 1.5.10: DO NOT EDIT THIS FILE

package us.ihmc.remotecaptury;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import static us.ihmc.remotecaptury.global.remotecaptury.*;


@Properties(inherit = us.ihmc.remotecaptury.RemoteCapturyConfig.class)
public class CapturyStopTrackingPacket extends Pointer {
    static { Loader.load(); }
    /** Default native constructor. */
    public CapturyStopTrackingPacket() { super((Pointer)null); allocate(); }
    /** Native array allocator. Access with {@link Pointer#position(long)}. */
    public CapturyStopTrackingPacket(long size) { super((Pointer)null); allocateArray(size); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public CapturyStopTrackingPacket(Pointer p) { super(p); }
    private native void allocate();
    private native void allocateArray(long size);
    @Override public CapturyStopTrackingPacket position(long position) {
        return (CapturyStopTrackingPacket)super.position(position);
    }
    @Override public CapturyStopTrackingPacket getPointer(long i) {
        return new CapturyStopTrackingPacket((Pointer)this).offsetAddress(i);
    }

	public native int type(); public native CapturyStopTrackingPacket type(int setter); // capturyStopTracking or capturyDeleteActor or capturyRescaleActor or capturyRecolorActor
	public native int size(); public native CapturyStopTrackingPacket size(int setter);
	public native int actor(); public native CapturyStopTrackingPacket actor(int setter);
}
