// Targeted by JavaCPP version 1.5.10: DO NOT EDIT THIS FILE

package us.ihmc.remotecaptury;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import static us.ihmc.remotecaptury.global.remotecaptury.*;


// sent to client
// as a reply to capturyGetImage or for streamed cameras
//
@Properties(inherit = us.ihmc.remotecaptury.RemoteCapturyConfig.class)
public class CapturyImageHeaderPacket extends Pointer {
    static { Loader.load(); }
    /** Default native constructor. */
    public CapturyImageHeaderPacket() { super((Pointer)null); allocate(); }
    /** Native array allocator. Access with {@link Pointer#position(long)}. */
    public CapturyImageHeaderPacket(long size) { super((Pointer)null); allocateArray(size); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public CapturyImageHeaderPacket(Pointer p) { super(p); }
    private native void allocate();
    private native void allocateArray(long size);
    @Override public CapturyImageHeaderPacket position(long position) {
        return (CapturyImageHeaderPacket)super.position(position);
    }
    @Override public CapturyImageHeaderPacket getPointer(long i) {
        return new CapturyImageHeaderPacket((Pointer)this).offsetAddress(i);
    }

	public native int type(); public native CapturyImageHeaderPacket type(int setter);		// capturyImageHeader, capturyStreamedImageHeader
	public native int size(); public native CapturyImageHeaderPacket size(int setter);

	public native int actor(); public native CapturyImageHeaderPacket actor(int setter);		// for capturyStreamedImageHeader this is the camera id
	public native @Cast("uint64_t") long timestamp(); public native CapturyImageHeaderPacket timestamp(long setter);
	public native @Cast("uint32_t") int fourcc(); public native CapturyImageHeaderPacket fourcc(int setter);		// image compression format
	public native int width(); public native CapturyImageHeaderPacket width(int setter);
	public native int height(); public native CapturyImageHeaderPacket height(int setter);
	public native int dataPacketSize(); public native CapturyImageHeaderPacket dataPacketSize(int setter);	// size of data packets
	public native int dataSize(); public native CapturyImageHeaderPacket dataSize(int setter);
}
