// Targeted by JavaCPP version 1.5.10: DO NOT EDIT THIS FILE

package us.ihmc.remotecaptury;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import static us.ihmc.remotecaptury.global.remotecaptury.*;


// sent to server
@Properties(inherit = us.ihmc.remotecaptury.RemoteCapturyConfig.class)
public class CapturyGetMarkerTransformPacket extends Pointer {
    static { Loader.load(); }
    /** Default native constructor. */
    public CapturyGetMarkerTransformPacket() { super((Pointer)null); allocate(); }
    /** Native array allocator. Access with {@link Pointer#position(long)}. */
    public CapturyGetMarkerTransformPacket(long size) { super((Pointer)null); allocateArray(size); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public CapturyGetMarkerTransformPacket(Pointer p) { super(p); }
    private native void allocate();
    private native void allocateArray(long size);
    @Override public CapturyGetMarkerTransformPacket position(long position) {
        return (CapturyGetMarkerTransformPacket)super.position(position);
    }
    @Override public CapturyGetMarkerTransformPacket getPointer(long i) {
        return new CapturyGetMarkerTransformPacket((Pointer)this).offsetAddress(i);
    }

	public native int type(); public native CapturyGetMarkerTransformPacket type(int setter);	// capturyGetMarkerTransform
	public native int size(); public native CapturyGetMarkerTransformPacket size(int setter);

	public native int actor(); public native CapturyGetMarkerTransformPacket actor(int setter);
	public native int joint(); public native CapturyGetMarkerTransformPacket joint(int setter);
}
