// Targeted by JavaCPP version 1.5.10: DO NOT EDIT THIS FILE

package us.ihmc.remotecaptury;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import static us.ihmc.remotecaptury.global.remotecaptury.*;


// sent to client
// as a reply to CapturyRequestPacket = capturyCameras
@Properties(inherit = us.ihmc.remotecaptury.RemoteCapturyConfig.class)
public class CapturyCamerasPacket extends Pointer {
    static { Loader.load(); }
    /** Default native constructor. */
    public CapturyCamerasPacket() { super((Pointer)null); allocate(); }
    /** Native array allocator. Access with {@link Pointer#position(long)}. */
    public CapturyCamerasPacket(long size) { super((Pointer)null); allocateArray(size); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public CapturyCamerasPacket(Pointer p) { super(p); }
    private native void allocate();
    private native void allocateArray(long size);
    @Override public CapturyCamerasPacket position(long position) {
        return (CapturyCamerasPacket)super.position(position);
    }
    @Override public CapturyCamerasPacket getPointer(long i) {
        return new CapturyCamerasPacket((Pointer)this).offsetAddress(i);
    }

	public native int type(); public native CapturyCamerasPacket type(int setter);	// capturyCameras
	public native int size(); public native CapturyCamerasPacket size(int setter);	// size of full message including type and size

	public native int numCameras(); public native CapturyCamerasPacket numCameras(int setter);
}
