// Targeted by JavaCPP version 1.5.10: DO NOT EDIT THIS FILE

package us.ihmc.remotecaptury;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import static us.ihmc.remotecaptury.global.remotecaptury.*;


@Properties(inherit = us.ihmc.remotecaptury.RemoteCapturyConfig.class)
public class CapturyDepthImage extends Pointer {
    static { Loader.load(); }
    /** Default native constructor. */
    public CapturyDepthImage() { super((Pointer)null); allocate(); }
    /** Native array allocator. Access with {@link Pointer#position(long)}. */
    public CapturyDepthImage(long size) { super((Pointer)null); allocateArray(size); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public CapturyDepthImage(Pointer p) { super(p); }
    private native void allocate();
    private native void allocateArray(long size);
    @Override public CapturyDepthImage position(long position) {
        return (CapturyDepthImage)super.position(position);
    }
    @Override public CapturyDepthImage getPointer(long i) {
        return new CapturyDepthImage((Pointer)this).offsetAddress(i);
    }

	public native int width(); public native CapturyDepthImage width(int setter);
	public native int height(); public native CapturyDepthImage height(int setter);
	public native int camera(); public native CapturyDepthImage camera(int setter);
	public native @Cast("uint64_t") long timestamp(); public native CapturyDepthImage timestamp(long setter);	// in microseconds
	public native @Cast("uint16_t*") ShortPointer data(); public native CapturyDepthImage data(ShortPointer setter);		// packed image data: stride = width*2 bytes
}
