// Targeted by JavaCPP version 1.5.10: DO NOT EDIT THIS FILE

package us.ihmc.remotecaptury;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import static us.ihmc.remotecaptury.global.remotecaptury.*;


// sent to client
// as a reply to CapturyRequestPacket = capturyActors
@Properties(inherit = us.ihmc.remotecaptury.RemoteCapturyConfig.class)
public class CapturyActorBlendShapesPacket extends Pointer {
    static { Loader.load(); }
    /** Default native constructor. */
    public CapturyActorBlendShapesPacket() { super((Pointer)null); allocate(); }
    /** Native array allocator. Access with {@link Pointer#position(long)}. */
    public CapturyActorBlendShapesPacket(long size) { super((Pointer)null); allocateArray(size); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public CapturyActorBlendShapesPacket(Pointer p) { super(p); }
    private native void allocate();
    private native void allocateArray(long size);
    @Override public CapturyActorBlendShapesPacket position(long position) {
        return (CapturyActorBlendShapesPacket)super.position(position);
    }
    @Override public CapturyActorBlendShapesPacket getPointer(long i) {
        return new CapturyActorBlendShapesPacket((Pointer)this).offsetAddress(i);
    }

	public native int type(); public native CapturyActorBlendShapesPacket type(int setter);		// capturyActorBlendShapes
	public native int size(); public native CapturyActorBlendShapesPacket size(int setter);		// size of full message including type and size

	public native int actorId(); public native CapturyActorBlendShapesPacket actorId(int setter);
	public native int numBlendShapes(); public native CapturyActorBlendShapesPacket numBlendShapes(int setter);
	public native @Cast("char") byte blendShapeNames(int i); public native CapturyActorBlendShapesPacket blendShapeNames(int i, byte setter);
	@MemberGetter public native @Cast("char*") BytePointer blendShapeNames();
}
