// Targeted by JavaCPP version 1.5.10: DO NOT EDIT THIS FILE

package us.ihmc.remotecaptury;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import static us.ihmc.remotecaptury.global.remotecaptury.*;


// sent to client
// as a reply to CapturyRequestPacket = capturyActors
@Properties(inherit = us.ihmc.remotecaptury.RemoteCapturyConfig.class)
public class CapturyActorPacket extends Pointer {
    static { Loader.load(); }
    /** Default native constructor. */
    public CapturyActorPacket() { super((Pointer)null); allocate(); }
    /** Native array allocator. Access with {@link Pointer#position(long)}. */
    public CapturyActorPacket(long size) { super((Pointer)null); allocateArray(size); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public CapturyActorPacket(Pointer p) { super(p); }
    private native void allocate();
    private native void allocateArray(long size);
    @Override public CapturyActorPacket position(long position) {
        return (CapturyActorPacket)super.position(position);
    }
    @Override public CapturyActorPacket getPointer(long i) {
        return new CapturyActorPacket((Pointer)this).offsetAddress(i);
    }

	public native int type(); public native CapturyActorPacket type(int setter);		// capturyActor or capturyActor2 or capturyActor3
	public native int size(); public native CapturyActorPacket size(int setter);		// size of full message including type and size

	public native @Cast("char") byte name(int i); public native CapturyActorPacket name(int i, byte setter);
	@MemberGetter public native @Cast("char*") BytePointer name();
	public native int id(); public native CapturyActorPacket id(int setter);
	public native int numJoints(); public native CapturyActorPacket numJoints(int setter);
	public native @ByRef CapturyJointPacket joints(int i); public native CapturyActorPacket joints(int i, CapturyJointPacket setter);
	@MemberGetter public native CapturyJointPacket joints();
}
