// Targeted by JavaCPP version 1.5.10: DO NOT EDIT THIS FILE

package us.ihmc.remotecaptury;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import static us.ihmc.remotecaptury.global.remotecaptury.*;


// sent to client
// as a reply to CapturyRequestPacket = capturyActors
// if the CapturyActorPacket becomes too big send this one
@Properties(inherit = us.ihmc.remotecaptury.RemoteCapturyConfig.class)
public class CapturyActorContinuedPacket extends Pointer {
    static { Loader.load(); }
    /** Default native constructor. */
    public CapturyActorContinuedPacket() { super((Pointer)null); allocate(); }
    /** Native array allocator. Access with {@link Pointer#position(long)}. */
    public CapturyActorContinuedPacket(long size) { super((Pointer)null); allocateArray(size); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public CapturyActorContinuedPacket(Pointer p) { super(p); }
    private native void allocate();
    private native void allocateArray(long size);
    @Override public CapturyActorContinuedPacket position(long position) {
        return (CapturyActorContinuedPacket)super.position(position);
    }
    @Override public CapturyActorContinuedPacket getPointer(long i) {
        return new CapturyActorContinuedPacket((Pointer)this).offsetAddress(i);
    }

	public native int type(); public native CapturyActorContinuedPacket type(int setter);		// capturyActorContinued
	public native int size(); public native CapturyActorContinuedPacket size(int setter);		// size of full message including type and size

	public native int id(); public native CapturyActorContinuedPacket id(int setter);		// actor id
	public native int startJoint(); public native CapturyActorContinuedPacket startJoint(int setter);
	public native @ByRef CapturyJointPacket joints(int i); public native CapturyActorContinuedPacket joints(int i, CapturyJointPacket setter);
	@MemberGetter public native CapturyJointPacket joints();
}
