// Targeted by JavaCPP version 1.5.10: DO NOT EDIT THIS FILE

package us.ihmc.remotecaptury;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import static us.ihmc.remotecaptury.global.remotecaptury.*;


@Properties(inherit = us.ihmc.remotecaptury.RemoteCapturyConfig.class)
public class CapturyTransform extends Pointer {
    static { Loader.load(); }
    /** Default native constructor. */
    public CapturyTransform() { super((Pointer)null); allocate(); }
    /** Native array allocator. Access with {@link Pointer#position(long)}. */
    public CapturyTransform(long size) { super((Pointer)null); allocateArray(size); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public CapturyTransform(Pointer p) { super(p); }
    private native void allocate();
    private native void allocateArray(long size);
    @Override public CapturyTransform position(long position) {
        return (CapturyTransform)super.position(position);
    }
    @Override public CapturyTransform getPointer(long i) {
        return new CapturyTransform((Pointer)this).offsetAddress(i);
    }

	public native float translation(int i); public native CapturyTransform translation(int i, float setter);
	@MemberGetter public native FloatPointer translation();	// translation
	public native float rotation(int i); public native CapturyTransform rotation(int i, float setter);
	@MemberGetter public native FloatPointer rotation();	// XYZ Euler angles
}
