// Targeted by JavaCPP version 1.5.10: DO NOT EDIT THIS FILE

package us.ihmc.remotecaptury;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import static us.ihmc.remotecaptury.global.remotecaptury.*;


@Properties(inherit = us.ihmc.remotecaptury.RemoteCapturyConfig.class)
public class CapturyCornerDetection extends Pointer {
    static { Loader.load(); }
    /** Default native constructor. */
    public CapturyCornerDetection() { super((Pointer)null); allocate(); }
    /** Native array allocator. Access with {@link Pointer#position(long)}. */
    public CapturyCornerDetection(long size) { super((Pointer)null); allocateArray(size); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public CapturyCornerDetection(Pointer p) { super(p); }
    private native void allocate();
    private native void allocateArray(long size);
    @Override public CapturyCornerDetection position(long position) {
        return (CapturyCornerDetection)super.position(position);
    }
    @Override public CapturyCornerDetection getPointer(long i) {
        return new CapturyCornerDetection((Pointer)this).offsetAddress(i);
    }

	public native int camera(); public native CapturyCornerDetection camera(int setter);
	public native @Name("position") float _position(int i); public native CapturyCornerDetection _position(int i, float setter);
	@MemberGetter public native @Name("position") FloatPointer _position();
	public native float boardCoordinates(int i); public native CapturyCornerDetection boardCoordinates(int i, float setter);
	@MemberGetter public native FloatPointer boardCoordinates();
}
