// Targeted by JavaCPP version 1.5.10: DO NOT EDIT THIS FILE

package us.ihmc.remotecaptury;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import static us.ihmc.remotecaptury.global.remotecaptury.*;


@Properties(inherit = us.ihmc.remotecaptury.RemoteCapturyConfig.class)
public class CapturySnapActorPacket extends Pointer {
    static { Loader.load(); }
    /** Default native constructor. */
    public CapturySnapActorPacket() { super((Pointer)null); allocate(); }
    /** Native array allocator. Access with {@link Pointer#position(long)}. */
    public CapturySnapActorPacket(long size) { super((Pointer)null); allocateArray(size); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public CapturySnapActorPacket(Pointer p) { super(p); }
    private native void allocate();
    private native void allocateArray(long size);
    @Override public CapturySnapActorPacket position(long position) {
        return (CapturySnapActorPacket)super.position(position);
    }
    @Override public CapturySnapActorPacket getPointer(long i) {
        return new CapturySnapActorPacket((Pointer)this).offsetAddress(i);
    }

	public native int type(); public native CapturySnapActorPacket type(int setter); // capturySnapActor
	public native int size(); public native CapturySnapActorPacket size(int setter);
	public native float x(); public native CapturySnapActorPacket x(float setter);
	public native float z(); public native CapturySnapActorPacket z(float setter);
	public native float heading(); public native CapturySnapActorPacket heading(float setter);
}
