// Targeted by JavaCPP version 1.5.10: DO NOT EDIT THIS FILE

package us.ihmc.remotecaptury;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import static us.ihmc.remotecaptury.global.remotecaptury.*;


@Properties(inherit = us.ihmc.remotecaptury.RemoteCapturyConfig.class)
public class CapturyBlendShape extends Pointer {
    static { Loader.load(); }
    /** Default native constructor. */
    public CapturyBlendShape() { super((Pointer)null); allocate(); }
    /** Native array allocator. Access with {@link Pointer#position(long)}. */
    public CapturyBlendShape(long size) { super((Pointer)null); allocateArray(size); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public CapturyBlendShape(Pointer p) { super(p); }
    private native void allocate();
    private native void allocateArray(long size);
    @Override public CapturyBlendShape position(long position) {
        return (CapturyBlendShape)super.position(position);
    }
    @Override public CapturyBlendShape getPointer(long i) {
        return new CapturyBlendShape((Pointer)this).offsetAddress(i);
    }

	public native @Cast("char") byte name(int i); public native CapturyBlendShape name(int i, byte setter);
	@MemberGetter public native @Cast("char*") BytePointer name();
}
