// Targeted by JavaCPP version 1.5.10: DO NOT EDIT THIS FILE

package us.ihmc.remotecaptury;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import static us.ihmc.remotecaptury.global.remotecaptury.*;


// sent to client
// part of CapturyActorPacket
@Properties(inherit = us.ihmc.remotecaptury.RemoteCapturyConfig.class)
public class CapturyJointPacket3 extends Pointer {
    static { Loader.load(); }
    /** Default native constructor. */
    public CapturyJointPacket3() { super((Pointer)null); allocate(); }
    /** Native array allocator. Access with {@link Pointer#position(long)}. */
    public CapturyJointPacket3(long size) { super((Pointer)null); allocateArray(size); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public CapturyJointPacket3(Pointer p) { super(p); }
    private native void allocate();
    private native void allocateArray(long size);
    @Override public CapturyJointPacket3 position(long position) {
        return (CapturyJointPacket3)super.position(position);
    }
    @Override public CapturyJointPacket3 getPointer(long i) {
        return new CapturyJointPacket3((Pointer)this).offsetAddress(i);
    }

	public native int parent(); public native CapturyJointPacket3 parent(int setter);
	public native float offset(int i); public native CapturyJointPacket3 offset(int i, float setter);
	@MemberGetter public native FloatPointer offset();
	public native float orientation(int i); public native CapturyJointPacket3 orientation(int i, float setter);
	@MemberGetter public native FloatPointer orientation();
	public native float scale(int i); public native CapturyJointPacket3 scale(int i, float setter);
	@MemberGetter public native FloatPointer scale();	// if scale[0] == -1: this is a blend shape
	public native @Cast("char") byte name(int i); public native CapturyJointPacket3 name(int i, byte setter);
	@MemberGetter public native @Cast("char*") BytePointer name();		// zero terminated joint name
}
