// Targeted by JavaCPP version 1.5.10: DO NOT EDIT THIS FILE

package us.ihmc.remotecaptury;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import static us.ihmc.remotecaptury.global.remotecaptury.*;


@Properties(inherit = us.ihmc.remotecaptury.RemoteCapturyConfig.class)
public class CapturySnapActorPacket2 extends Pointer {
    static { Loader.load(); }
    /** Default native constructor. */
    public CapturySnapActorPacket2() { super((Pointer)null); allocate(); }
    /** Native array allocator. Access with {@link Pointer#position(long)}. */
    public CapturySnapActorPacket2(long size) { super((Pointer)null); allocateArray(size); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public CapturySnapActorPacket2(Pointer p) { super(p); }
    private native void allocate();
    private native void allocateArray(long size);
    @Override public CapturySnapActorPacket2 position(long position) {
        return (CapturySnapActorPacket2)super.position(position);
    }
    @Override public CapturySnapActorPacket2 getPointer(long i) {
        return new CapturySnapActorPacket2((Pointer)this).offsetAddress(i);
    }

	public native int type(); public native CapturySnapActorPacket2 type(int setter); // capturySnapActor
	public native int size(); public native CapturySnapActorPacket2 size(int setter);
	public native float x(); public native CapturySnapActorPacket2 x(float setter);
	public native float z(); public native CapturySnapActorPacket2 z(float setter);
	public native float radius(); public native CapturySnapActorPacket2 radius(float setter);
	public native float heading(); public native CapturySnapActorPacket2 heading(float setter);
	public native @Cast("uint8_t") byte snapMethod(); public native CapturySnapActorPacket2 snapMethod(byte setter);
	public native @Cast("uint8_t") byte quickScaling(); public native CapturySnapActorPacket2 quickScaling(byte setter);
	public native @Cast("char") byte skeletonName(int i); public native CapturySnapActorPacket2 skeletonName(int i, byte setter);
	@MemberGetter public native @Cast("char*") BytePointer skeletonName();
}
