// Targeted by JavaCPP version 1.5.10: DO NOT EDIT THIS FILE

package us.ihmc.remotecaptury;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import static us.ihmc.remotecaptury.global.remotecaptury.*;


// sent to client
// as a reply to capturyGetMarkerTransform
@Properties(inherit = us.ihmc.remotecaptury.RemoteCapturyConfig.class)
public class CapturyMarkerTransformPacket extends Pointer {
    static { Loader.load(); }
    /** Default native constructor. */
    public CapturyMarkerTransformPacket() { super((Pointer)null); allocate(); }
    /** Native array allocator. Access with {@link Pointer#position(long)}. */
    public CapturyMarkerTransformPacket(long size) { super((Pointer)null); allocateArray(size); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public CapturyMarkerTransformPacket(Pointer p) { super(p); }
    private native void allocate();
    private native void allocateArray(long size);
    @Override public CapturyMarkerTransformPacket position(long position) {
        return (CapturyMarkerTransformPacket)super.position(position);
    }
    @Override public CapturyMarkerTransformPacket getPointer(long i) {
        return new CapturyMarkerTransformPacket((Pointer)this).offsetAddress(i);
    }

	public native int type(); public native CapturyMarkerTransformPacket type(int setter);	// capturyMarkerTransform
	public native int size(); public native CapturyMarkerTransformPacket size(int setter);

	public native @Cast("uint64_t") long timestamp(); public native CapturyMarkerTransformPacket timestamp(long setter);

	public native int actor(); public native CapturyMarkerTransformPacket actor(int setter);
	public native int joint(); public native CapturyMarkerTransformPacket joint(int setter);

	public native float rotation(int i); public native CapturyMarkerTransformPacket rotation(int i, float setter);
	@MemberGetter public native FloatPointer rotation(); // XYZ Euler angles
	public native float translation(int i); public native CapturyMarkerTransformPacket translation(int i, float setter);
	@MemberGetter public native FloatPointer translation();
}
