// Targeted by JavaCPP version 1.5.10: DO NOT EDIT THIS FILE

package us.ihmc.remotecaptury;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import static us.ihmc.remotecaptury.global.remotecaptury.*;


@Properties(inherit = us.ihmc.remotecaptury.RemoteCapturyConfig.class)
public class CapturyActor extends Pointer {
    static { Loader.load(); }
    /** Default native constructor. */
    public CapturyActor() { super((Pointer)null); allocate(); }
    /** Native array allocator. Access with {@link Pointer#position(long)}. */
    public CapturyActor(long size) { super((Pointer)null); allocateArray(size); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public CapturyActor(Pointer p) { super(p); }
    private native void allocate();
    private native void allocateArray(long size);
    @Override public CapturyActor position(long position) {
        return (CapturyActor)super.position(position);
    }
    @Override public CapturyActor getPointer(long i) {
        return new CapturyActor((Pointer)this).offsetAddress(i);
    }

	public native @Cast("char") byte name(int i); public native CapturyActor name(int i, byte setter);
	@MemberGetter public native @Cast("char*") BytePointer name();
	public native int id(); public native CapturyActor id(int setter);
	public native int numJoints(); public native CapturyActor numJoints(int setter);
	public native CapturyJoint joints(); public native CapturyActor joints(CapturyJoint setter);
	public native int numBlobs(); public native CapturyActor numBlobs(int setter);
	public native CapturyBlob blobs(); public native CapturyActor blobs(CapturyBlob setter);
	public native int numBlendShapes(); public native CapturyActor numBlendShapes(int setter);
	public native CapturyBlendShape blendShapes(); public native CapturyActor blendShapes(CapturyBlendShape setter);
}
