// Targeted by JavaCPP version 1.5.10: DO NOT EDIT THIS FILE

package us.ihmc.remotecaptury;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import static us.ihmc.remotecaptury.global.remotecaptury.*;


// sent to client
// as a reply to CapturyRequestPacket = capturyDaySessionShot
@Properties(inherit = us.ihmc.remotecaptury.RemoteCapturyConfig.class)
public class CapturyDaySessionShotPacket extends Pointer {
    static { Loader.load(); }
    /** Default native constructor. */
    public CapturyDaySessionShotPacket() { super((Pointer)null); allocate(); }
    /** Native array allocator. Access with {@link Pointer#position(long)}. */
    public CapturyDaySessionShotPacket(long size) { super((Pointer)null); allocateArray(size); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public CapturyDaySessionShotPacket(Pointer p) { super(p); }
    private native void allocate();
    private native void allocateArray(long size);
    @Override public CapturyDaySessionShotPacket position(long position) {
        return (CapturyDaySessionShotPacket)super.position(position);
    }
    @Override public CapturyDaySessionShotPacket getPointer(long i) {
        return new CapturyDaySessionShotPacket((Pointer)this).offsetAddress(i);
    }

	public native int type(); public native CapturyDaySessionShotPacket type(int setter);	// capturyDaySessionShot
	public native int size(); public native CapturyDaySessionShotPacket size(int setter);	// size of full message including type and size

	public native @Cast("char") byte day(int i); public native CapturyDaySessionShotPacket day(int i, byte setter);
	@MemberGetter public native @Cast("char*") BytePointer day();
	public native @Cast("char") byte session(int i); public native CapturyDaySessionShotPacket session(int i, byte setter);
	@MemberGetter public native @Cast("char*") BytePointer session();
	public native @Cast("char") byte shot(int i); public native CapturyDaySessionShotPacket shot(int i, byte setter);
	@MemberGetter public native @Cast("char*") BytePointer shot();
}
