// Targeted by JavaCPP version 1.5.10: DO NOT EDIT THIS FILE

package us.ihmc.remotecaptury;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import static us.ihmc.remotecaptury.global.remotecaptury.*;


@Properties(inherit = us.ihmc.remotecaptury.RemoteCapturyConfig.class)
public class CapturyActorModeChangedPacket extends Pointer {
    static { Loader.load(); }
    /** Default native constructor. */
    public CapturyActorModeChangedPacket() { super((Pointer)null); allocate(); }
    /** Native array allocator. Access with {@link Pointer#position(long)}. */
    public CapturyActorModeChangedPacket(long size) { super((Pointer)null); allocateArray(size); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public CapturyActorModeChangedPacket(Pointer p) { super(p); }
    private native void allocate();
    private native void allocateArray(long size);
    @Override public CapturyActorModeChangedPacket position(long position) {
        return (CapturyActorModeChangedPacket)super.position(position);
    }
    @Override public CapturyActorModeChangedPacket getPointer(long i) {
        return new CapturyActorModeChangedPacket((Pointer)this).offsetAddress(i);
    }

	public native int type(); public native CapturyActorModeChangedPacket type(int setter); // capturyActorModeChanged
	public native int size(); public native CapturyActorModeChangedPacket size(int setter);
	public native int actor(); public native CapturyActorModeChangedPacket actor(int setter);
	public native int mode(); public native CapturyActorModeChangedPacket mode(int setter);
}
