// Targeted by JavaCPP version 1.5.10: DO NOT EDIT THIS FILE

package us.ihmc.remotecaptury;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import static us.ihmc.remotecaptury.global.remotecaptury.*;


// sent to client
@Properties(inherit = us.ihmc.remotecaptury.RemoteCapturyConfig.class)
public class CapturyAnglesPacket extends Pointer {
    static { Loader.load(); }
    /** Default native constructor. */
    public CapturyAnglesPacket() { super((Pointer)null); allocate(); }
    /** Native array allocator. Access with {@link Pointer#position(long)}. */
    public CapturyAnglesPacket(long size) { super((Pointer)null); allocateArray(size); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public CapturyAnglesPacket(Pointer p) { super(p); }
    private native void allocate();
    private native void allocateArray(long size);
    @Override public CapturyAnglesPacket position(long position) {
        return (CapturyAnglesPacket)super.position(position);
    }
    @Override public CapturyAnglesPacket getPointer(long i) {
        return new CapturyAnglesPacket((Pointer)this).offsetAddress(i);
    }

	public native int type(); public native CapturyAnglesPacket type(int setter);	// capturyAngles
	public native int size(); public native CapturyAnglesPacket size(int setter);

	public native int actor(); public native CapturyAnglesPacket actor(int setter);
	public native @Cast("uint64_t") long timestamp(); public native CapturyAnglesPacket timestamp(long setter);
	public native @Cast("uint16_t") short numAngles(); public native CapturyAnglesPacket numAngles(short setter);
	public native @ByRef CapturyAngleData angles(int i); public native CapturyAnglesPacket angles(int i, CapturyAngleData setter);
	@MemberGetter public native CapturyAngleData angles();
}
