name: Build remotecaptury-java Windows natives

on:
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: [windows-2019]
    steps:
      - uses: actions/checkout@v4
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          vsversion: 2019
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Check Java/Gradle versions
        run: |
          java --version
          gradle --version
      - name: Compile native library
        run: |
          bash.exe cppbuild.bash
      - name: Run tests
        run: |
          ./gradlew test
      - name: Commit native libraries
        uses: EndBug/add-and-commit@v9
        with:
          add: '*.dll' # Only commit generated java from Linux
          author_name: ihmc-rosie
          author_email: rosie@ihmc.us
          message: 'Rebuild natives for Windows'
          push: true